onflow/FRW-Android

- app/build.gradle
- app/src/main/java/io/outblock/lilico/manager/LaunchManager.kt
- app/src/main/java/io/outblock/lilico/manager/account/BalanceManager.kt
- app/src/main/java/io/outblock/lilico/manager/account/WalletFetcher.kt
- app/src/main/java/io/outblock/lilico/manager/app/AppLifecycleObserver.kt
- app/src/main/java/io/outblock/lilico/manager/app/ChainNetwork.kt
- app/src/main/java/io/outblock/lilico/manager/flowjvm/CadenceExecutor.kt
- app/src/main/java/io/outblock/lilico/manager/staking/StakingManager.kt
- app/src/main/java/io/outblock/lilico/manager/wallet/WalletManager.kt
- app/src/main/java/io/outblock/lilico/manager/walletconnect/WalletConnect.kt
- app/src/main/java/io/outblock/lilico/manager/walletconnect/WalletConnectDelegate.kt
- app/src/main/java/io/outblock/lilico/page/dialog/processing/send/SendProcessingViewModel.kt
- app/src/main/java/io/outblock/lilico/page/profile/subpage/wallet/childaccountdetail/Utils.kt
- app/src/main/java/io/outblock/lilico/page/receive/ReceiveViewModel.kt
- app/src/main/java/io/outblock/lilico/page/send/nft/NftSendAddressDialog.kt
- app/src/main/java/io/outblock/lilico/page/send/nft/confirm/NftSendConfirmViewModel.kt
- app/src/main/java/io/outblock/lilico/page/send/transaction/subpage/amount/presenter/SendAmountPresenter.kt
- app/src/main/java/io/outblock/lilico/page/send/transaction/subpage/transaction/TransactionViewModel.kt
- app/src/main/java/io/outblock/lilico/page/staking/amount/dialog/StakingAmountConfirmDialog.kt
- app/src/main/java/io/outblock/lilico/page/staking/detail/StakingDetailViewModel.kt
- app/src/main/java/io/outblock/lilico/page/staking/detail/presenter/StakingDetailPresenter.kt
- app/src/main/java/io/outblock/lilico/page/wallet/WalletFragmentViewModel.kt
- app/src/main/java/io/outblock/lilico/page/wallet/presenter/WalletCoinItemPresenter.kt
- app/src/main/java/io/outblock/lilico/utils/QRCodeUtils.kt
- app/src/main/java/io/outblock/lilico/utils/extensions/NumberExts.kt
- app/src/main/res/layout/dialog_fcl_authz.xml
- app/src/main/res/layout/dialog_send_confirm.xml
- app/src/main/res/layout/dialog_swap_token_confirm.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/network_security_config.xml
- fix token list and balance empty
- fix staking info empty
- fix staking detail display and claim zero limit issue
- fix transaction from address issue
> fix:  get token list and staking info with wrong address

- app/src/main/java/com/flowfoundation/wallet/manager/account/BalanceManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/coin/FlowCoinListManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/coin/TokenStateManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/addtoken/AddTokenViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/wallet/WalletFragmentViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/wallet/presenter/WalletHeaderPresenter.kt
- gradle.properties
- fix this [issue](https://github.com/Outblock/FRW-Android/issues/452)
- updated the TokenState logic for determining whether it’s the same token.
> fix: add token issue

- app/src/main/java/com/flowfoundation/wallet/manager/evm/Utils.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/Cadence.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
- gradle.properties
> feat: evm tx id calculation

- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/Cadence.kt
- app/src/main/java/com/flowfoundation/wallet/manager/wallet/WalletManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/nft/confirm/NftSendConfirmViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/transaction/TransactionViewModel.kt
> Replace sending assets cadence with auto initialize account

- app/src/main/java/com/flowfoundation/wallet/manager/evm/Utils.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/Cadence.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
- app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnectRequestDispatcher.kt
- app/src/main/java/com/flowfoundation/wallet/widgets/webview/evm/EvmInterface.kt
> fix: contract call v2 scripts

- app/build.gradle
> fix: dropbox prod and dev key

- app/src/main/java/com/flowfoundation/wallet/manager/evm/Utils.kt
- gradle.properties
> fix: call contract value amount

- app/src/main/java/com/flowfoundation/wallet/page/receive/presenter/ReceivePresenter.kt
- app/src/main/res/layout/activity_receive.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
> fix: copy address

- gradle.properties
> feat: upgrade release version

- app/src/main/java/com/flowfoundation/wallet/manager/dropbox/DropboxBackupUtils.kt
- app/src/main/java/com/flowfoundation/wallet/manager/dropbox/DropboxServerHelper.kt
- app/src/main/java/com/flowfoundation/wallet/page/backup/multibackup/view/BackupOptionView.kt
- gradle.properties
> fix: dropbox file path

- app/src/main/java/com/flowfoundation/wallet/page/restore/keystore/viewmodel/KeyStoreRestoreViewModel.kt
> fix: keystore import hash algo

- app/src/main/res/values/strings.xml
- gradle.properties
> fix: copy change

- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-en-rUS/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-es-rUS/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-ja-rJP/strings.xml
- app/src/main/res/values-ko-rKR/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rHK/strings.xml
- app/src/main/res/values-zh-rSG/strings.xml
> feat: locale translations

- app/src/main/java/com/flowfoundation/wallet/manager/drive/GoogleDriveAuthActivity.kt
- gradle.properties
> fix: google drive scope request

- app/src/main/java/com/flowfoundation/wallet/page/send/transaction/presenter/TransactionSendPresenter.kt
Closes #562 
Re-order tabs to show My Accounts first on the send tokens flow.
New order is My Accounts > Recent > Address Book
> 562/ Re-order tabs to show My Accounts first

- app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnectResponse.kt
- app/src/main/java/com/flowfoundation/wallet/widgets/webview/fcl/FclScript.kt
> feat: add network info with account_proof script

- app/src/main/res/drawable/bg_empty_placeholder.xml
> fix: wrong empty placeholder

- app/src/main/res/layout/activity_main.xml
https://github.com/Outblock/FRW-Android/issues/565#issuecomment-2673552629
> Adjust padding under nav bar elements

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftdetail/presenter/NftDetailPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftdetail/widget/NftMorePopupMenu.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/avatar/ViewAvatarActivity.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/developer/presenter/DeveloperModePresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/wallet/childaccountedit/ChildAccountEditActivity.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/wallet/childaccountedit/presenter/ChildAccountEditPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/utils/CommonUtils.kt
- app/src/main/java/com/flowfoundation/wallet/utils/FileUtils.kt
- app/src/main/java/com/flowfoundation/wallet/utils/debug/fragments/debugViewer/DebugViewerFragment.kt
- app/src/main/java/com/flowfoundation/wallet/utils/image/PhotoPicker.kt
Closes #602 
Removed the READ_EXTERNAL_STORAGE permission and modified the logic for selecting the user profile avatar and saving NFT images.
[GooglePlay policy issue](https://play.google.com/console/u/0/developers/8838565086714989673/app/4973723674645133415/policy-center/issues/4987365554212960272/details)
> Remove the use of READ_EXTERNAL_STORAGE

- .github/CODEOWNERS
- .github/pull_request_template.md
- .github/workflows/check-linked-issues.yml
> [624] Add github workflow

- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceScript.kt
- app/src/main/java/com/flowfoundation/wallet/manager/nft/NftCollectionStateManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/transaction/TransactionStateManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/collectionlist/NftCollectionListViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/nft/confirm/NftSendConfirmViewModel.kt
- app/src/main/res/layout/activity_main.xml
- gradle.properties
Closes #626 #628 
https://github.com/user-attachments/assets/53df91ea-4105-44b4-a552-18272f6060ab
> fix: add collection button state

- app/src/main/java/com/flowfoundation/wallet/manager/account/BalanceManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/move/SelectNFTDialog.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/move/SelectNFTViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/widget/MoveTokenDialog.kt
- app/src/main/res/drawable/ic_arrows_horizontal.xml
- app/src/main/res/layout/dialog_move_token.xml
- app/src/main/res/layout/dialog_select_nft.xml
- Enables swapping and selecting From/To addresses for FT moves.
- This PR builds on top of https://github.com/Outblock/FRW-Android/pull/630, which should be merged first.
> FT move workflow

- app/src/main/java/com/flowfoundation/wallet/manager/nft/NftCollectionStateManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/collectionlist/NftCollectionListViewModel.kt
- app/src/main/res/drawable/ic_seed_phrase_advanced_open.xml
Closes #626 
Handled the judgment of collections with the same contract address but different contract names.
> fix: enable collection state

- app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/transaction/TransactionViewModel.kt
- gradle.properties
> fix: transaction listener

- app/src/main/java/com/flowfoundation/wallet/manager/account/BalanceManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/evm/EVMWalletManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/transaction/TransactionViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/model/MoveToken.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/provider/EVMAccountTokenProvider.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/provider/FlowAccountTokenProvider.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/provider/MoveTokenProvider.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/widget/MoveTokenDialog.kt
- app/src/main/java/com/flowfoundation/wallet/utils/Pattern.kt
- gradle.properties
Closes #650 
https://github.com/user-attachments/assets/ad52acd8-66ad-48e9-92b4-33204fb03b23
> fix: move token action

- app/src/main/java/com/flowfoundation/wallet/page/nft/move/SelectNFTDialog.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/move/SelectNFTViewModel.kt
> fix: batch move nft from address

- app/src/main/java/com/flowfoundation/wallet/manager/coin/FlowCoinListManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/amount/presenter/SendAmountPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/custom/model/CustomTokenItem.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/provider/EVMAccountTokenProvider.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/provider/FlowAccountTokenProvider.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/widget/MoveTokenDialog.kt
- app/src/main/java/com/flowfoundation/wallet/utils/extensions/TextViewExts.kt
Closes #659 #660 #661 #662 
Restrict token transfers from Cadence to Cadence to a maximum precision of 8 decimal places.
Restrict token transfers from the EVM to Cadence to the maximum precision supported by the specific token, with a maximum of 8 decimal places.
Restrict token transfers from Cadence to the EVM to the maximum precision supported by the specific token, with a maximum of 8 decimal places.
Restrict token transfers from the EVM to the EVM to the maximum precision supported by the specific token.
Cadence -> EVM / Cadence
EVM -> Cadence
EVM -> EVM
> Token Manipulation Parity

- app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletDappDelegate.kt
> fix: change walletconnect state log info

- app/src/main/res/layout/layout_browser.xml
- app/src/main/res/values/styles.xml
> Fix browser UI

- app/src/main/java/com/flowfoundation/wallet/page/wallet/sync/WalletSyncViewModel.kt
Closes #700 
https://dashboard.instabug.com/applications/flow-wallet/production/crashes/190?filters=%7B%22date_ms%22:%7B%22gte%22:1739404800000,%22lte%22:1741823999999,%22shortcutLabel%22:%22Last%2028%20days%22%7D,%22app_versions%22:%5B%22r2.7.6%20(222)%22,%22r2.7.1%20(212)%22,%22r2.6.3%20(208)%22%5D%7D
> Debug instabug crash #190

- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-en-rUS/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-es-rUS/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-ja-rJP/strings.xml
- app/src/main/res/values-ko-rKR/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
> Local translation

- app/src/main/java/com/flowfoundation/wallet/page/nft/move/model/NFTInfo.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/search/viewmodel/NFTInfoListViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/search/viewmodel/NFTItemListViewModel.kt
Closes #714 
https://github.com/user-attachments/assets/674771d0-731b-4d6b-90ef-e0155d182dd3
> feat: search nft improvement

- app/src/main/java/com/flowfoundation/wallet/page/browser/widgets/LilicoWebView.kt
Closes https://github.com/onflow/FRW-Android/issues/713
https://dashboard.instabug.com/applications/flow-wallet/production/crashes/239?filters=%7B%22date_ms%22:%7B%22shortcutLabel%22:%22Last%207%20days%22%7D%7D
> Debug instabug crash #239

- app/src/main/java/com/flowfoundation/wallet/page/wallet/presenter/WalletHeaderPresenter.kt
> fix: total balance showing up as blank

- app/src/main/java/com/flowfoundation/wallet/manager/account/BalanceManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/coin/TokenStateManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceScript.kt
- app/src/main/java/com/flowfoundation/wallet/manager/nft/NftCollectionStateManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/main/Utils.kt
> feat: simplify the logic of token balance and available flow balance

- app/src/main/java/com/flowfoundation/wallet/page/main/Utils.kt
- gradle.properties
> feat: display sidebar child account balance

- app/src/main/java/com/flowfoundation/wallet/network/model/NFTListResponse.kt
- app/src/main/java/com/flowfoundation/wallet/page/collection/CollectionActivity.kt
- app/src/main/java/com/flowfoundation/wallet/page/collection/CollectionViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/move/MoveNFTDialog.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftdetail/NftDetailActivity.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftdetail/NftDetailViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftdetail/presenter/NftDetailPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/NftViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/adapter/CollectionTabsAdapter.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/presenter/CollectionLineItemPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/presenter/CollectionTabsPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/presenter/NFTListItemPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/presenter/SelectionItemPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/utils/NftCacheUtils.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/utils/NftListRequester.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/wallet/childaccountdetail/presenter/AccessibleNftCollectionPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/nft/NftSendAddressDialog.kt
> fix: collection with same contract name

- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-en-rUS/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-es-rUS/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-ja-rJP/strings.xml
- app/src/main/res/values-ko-rKR/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> feat: change search nft copy

- app/src/main/java/com/flowfoundation/wallet/page/swap/dialog/select/SelectTokenDialog.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/detail/widget/MoveTokenDialog.kt
Fixes: If the user clicks the token button multiple times, the token list pops up multiple times. We need to ensure that it only pops up once.
https://github.com/onflow/FRW-Android/issues/646#issuecomment-2741971011
https://github.com/onflow/FRW-Android/issues/738
> 646/ Prevent opening select token dialog multiple times

- app/src/main/java/com/flowfoundation/wallet/page/scan/ScanBarcodeActivity.kt
> fix: optimize the QR code scanning

- app/src/main/java/com/flowfoundation/wallet/network/NetworkConst.kt
> feat: change dev endpoints

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/flowfoundation/wallet/page/browser/widgets/LilicoWebView.kt
> feat: add deeplink host

- app/src/main/res/values/colors.xml
Develop branch build currently failing due to lint warning
> Fix dev build

- app/src/main/java/com/flowfoundation/wallet/instabug/InstabugUtils.kt
- app/src/main/java/com/flowfoundation/wallet/manager/evm/EVMWalletManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/transaction/Transaction.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/transaction/Utils.kt
- app/src/main/java/com/flowfoundation/wallet/page/main/MainActivity.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/move/MoveNFTDialog.kt
- app/src/main/java/com/flowfoundation/wallet/page/nft/move/SelectNFTViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/presenter/ProfileFragmentPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/restore/multirestore/viewmodel/MultiRestoreViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/nft/confirm/NftSendConfirmViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/transaction/TransactionViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/utils/debug/fragments/debugViewer/DebugViewerFragment.kt
- app/src/main/java/com/flowfoundation/wallet/utils/error/Error.kt
- app/src/main/java/com/flowfoundation/wallet/utils/error/ErrorReporter.kt
> feat: instabug event

- app/src/main/java/com/flowfoundation/wallet/page/wallet/sync/WalletSyncViewModel.kt
> fix: instabug #190 coroutine resume issue

- app/build.gradle
- app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnect.kt
- app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnectDelegate.kt
- app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/Utils.kt
- gradle.properties
> fix: walletconnect pair

- app/src/main/java/com/flowfoundation/wallet/manager/blocklist/BlockManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/childaccount/ChildAccountList.kt
- app/src/main/java/com/flowfoundation/wallet/manager/evm/EVMWalletManager.kt
- app/src/main/java/com/flowfoundation/wallet/manager/flow/FlowCadenceApi.kt
- app/src/main/java/com/flowfoundation/wallet/utils/Log.kt
- app/src/main/java/com/flowfoundation/wallet/utils/error/Error.kt
> fix: remove the unnecessary reports

- app/src/main/java/com/flowfoundation/wallet/network/model/EVMTokenListResponse.kt
- app/src/main/java/com/flowfoundation/wallet/network/model/FlowTokenListResponse.kt
- app/src/main/java/com/flowfoundation/wallet/page/wallet/presenter/WalletHeaderPresenter.kt
> fix: token path and evm token balance issues

- gradle.properties
> feat: upgrade the version code

- app/src/main/java/com/flowfoundation/wallet/page/nft/move/MoveNFTDialog.kt
- gradle.properties
> Merge r2.8.5 with code 288 from develop to master

- gradle.properties
> fix: update the version code

- app/src/main/java/com/flowfoundation/wallet/page/browser/widgets/LilicoWebView.kt
- app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/Utils.kt
- app/src/main/java/com/flowfoundation/wallet/widgets/webview/JsInterface.kt
- app/src/main/res/values/strings.xml
- gradle.properties
> Merge r2.8.5 with version code 290 from develop to master

- app/src/main/java/com/flowfoundation/wallet/manager/config/NftCollectionConfig.kt
- app/src/main/java/com/flowfoundation/wallet/page/collection/presenter/CollectionContentPresenter.kt
> fix: nft collection external url

- app/src/main/java/com/flowfoundation/wallet/page/backup/BackupDetailActivity.kt
- app/src/main/java/com/flowfoundation/wallet/page/backup/model/BackupKey.kt
- app/src/main/java/com/flowfoundation/wallet/page/backup/presenter/BackupListItemPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/backup/viewmodel/WalletBackupViewModel.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/wallet/key/AccountKeyRevokeDialog.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/wallet/key/presenter/AccountKeyListItemPresenter.kt
- app/src/main/java/com/flowfoundation/wallet/page/walletcreate/fragments/username/WalletCreateUsernamePresenter.kt
> fix: valid jwt and key index

- gradle.properties
> feat: upgrade version code

- app/src/main/java/com/flowfoundation/wallet/manager/token/FungibleTokenListManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/token/addtoken/AddTokenViewModel.kt
> fix: display the added new token

- app/src/main/java/com/flowfoundation/wallet/utils/ImageViewUtils.kt
- gradle.properties
> fix: square avatar

- app/src/main/java/com/flowfoundation/wallet/page/explore/ExploreViewModel.kt
> fix: dapps category

- app/src/main/java/com/flowfoundation/wallet/utils/ContextUtils.kt
- app/src/main/java/com/flowfoundation/wallet/widgets/webview/fcl/FclMessageHandler.kt
> fix: webview context not activity

- app/src/main/java/com/flowfoundation/wallet/page/wallet/WalletFragmentViewModel.kt
> fix: livedata passing object references

- app/src/main/java/com/flowfoundation/wallet/page/wallet/WalletFragment.kt
- app/src/main/res/layout/fragment_coordinator_wallet.xml
> fix: enlarged the click area for scanning

- app/src/main/java/com/flowfoundation/wallet/manager/account/WalletFetcher.kt
- app/src/main/java/com/flowfoundation/wallet/manager/wallet/WalletManager.kt
- app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/developer/DeveloperModeViewModel.kt
Use firebase id as user identifier in place of username.
> Use firebase id as user identifier
