onflow/FRW-Android

app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/amount/presenter/SendAmountPresenter.kt
gradle.properties

Closes #425 
We are already using the available balance, so if the user has enabled gas fee free, the minimum balance should be 0.

fix: send available mount with gas fee free

---

app/src/main/java/com/flowfoundation/wallet/page/profile/widget/ProfileSwitchTipsBanner.kt

Closes https://github.com/onflow/FRW-Android/issues/743
- Replaced ioScope with lifecycleScope.launch
- Added early return in checkAndShowTips if view is not attached
- General error handling improvements

Instabug 57

---

app/src/main/java/com/flowfoundation/wallet/manager/config/AppConfig.kt
app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceScript.kt
app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/transaction/Transaction.kt
app/src/main/java/com/flowfoundation/wallet/network/NetworkConst.kt
app/src/main/java/com/flowfoundation/wallet/network/functions/Functions.kt
app/src/main/java/com/flowfoundation/wallet/page/nft/move/MoveNFTDialog.kt
app/src/main/java/com/flowfoundation/wallet/page/nft/move/SelectNFTDialog.kt

feat: cover bridge fee

---

.github/workflows/pr-build.yml
.github/workflows/release.yml

Point FWK to latest stable version

FWK release version

---

app/src/main/java/com/flowfoundation/wallet/manager/account/AccountInfoManager.kt
app/src/main/java/com/flowfoundation/wallet/page/nft/move/MoveNFTDialog.kt
app/src/main/java/com/flowfoundation/wallet/page/nft/move/SelectNFTDialog.kt
app/src/main/java/com/flowfoundation/wallet/page/profile/subpage/wallet/WalletSettingActivity.kt
app/src/main/java/com/flowfoundation/wallet/page/restore/keystore/PrivateKeyStoreCryptoProvider.kt
app/src/main/java/com/flowfoundation/wallet/page/restore/keystore/fragment/PrivateKeyInfoFragment.kt
app/src/main/java/com/flowfoundation/wallet/page/restore/keystore/fragment/PrivateKeyStoreInfoFragment.kt
app/src/main/java/com/flowfoundation/wallet/page/restore/keystore/fragment/SeedPhraseInfoFragment.kt
app/src/main/java/com/flowfoundation/wallet/page/security/recovery/SecurityPrivateKeyActivity.kt
app/src/main/java/com/flowfoundation/wallet/page/token/detail/widget/MoveTokenDialog.kt
app/src/main/res/layout/activity_security_public_key.xml
app/src/main/res/layout/dialog_move_nft.xml
app/src/main/res/layout/dialog_move_token.xml
app/src/main/res/layout/dialog_select_nft.xml

fix: private key display and move fee

---

app/build.gradle
app/src/main/java/com/flowfoundation/wallet/firebase/messaging/FirebaseMessaging.kt
app/src/main/java/com/flowfoundation/wallet/instabug/InstabugUtils.kt
app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
app/src/main/java/com/flowfoundation/wallet/manager/transaction/TransactionStateManager.kt
app/src/main/java/com/flowfoundation/wallet/manager/transaction/TransactionStateWatcher.kt
app/src/main/java/com/flowfoundation/wallet/mixpanel/MixpanelManager.kt
app/src/main/java/com/flowfoundation/wallet/network/NetworkConst.kt
app/src/main/java/com/flowfoundation/wallet/page/profile/presenter/ProfileFragmentPresenter.kt
app/src/main/java/com/flowfoundation/wallet/page/swap/Transactions.kt
app/src/main/java/com/flowfoundation/wallet/service/MessagingService.kt
app/src/main/java/com/flowfoundation/wallet/utils/ExceptionExt.kt
app/src/main/java/com/flowfoundation/wallet/utils/error/ErrorReporter.kt

feat: add flow transaction error report

---

app/src/main/java/com/flowfoundation/wallet/cache/AccountCacheManager.kt
app/src/main/java/com/flowfoundation/wallet/cache/UserPrefixCacheManager.kt
app/src/main/java/com/flowfoundation/wallet/manager/account/AccountManager.kt
app/src/main/java/com/flowfoundation/wallet/manager/account/WalletFetcher.kt
app/src/main/java/com/flowfoundation/wallet/manager/backup/GoogleDriveBackupUtils.kt
app/src/main/java/com/flowfoundation/wallet/manager/cadence/CadenceApiManager.kt
app/src/main/java/com/flowfoundation/wallet/manager/drive/GoogleDriveAuthActivity.kt
app/src/main/java/com/flowfoundation/wallet/manager/dropbox/DropboxBackupUtils.kt
app/src/main/java/com/flowfoundation/wallet/manager/evm/EVMWalletManager.kt
app/src/main/java/com/flowfoundation/wallet/manager/flowjvm/CadenceExecutor.kt
app/src/main/java/com/flowfoundation/wallet/manager/staking/StakingManager.kt
app/src/main/java/com/flowfoundation/wallet/network/UserRegisterUtils.kt
app/src/main/java/com/flowfoundation/wallet/page/backup/multibackup/viewmodel/BackupDropboxViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/backup/multibackup/viewmodel/BackupGoogleDriveViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/backup/multibackup/viewmodel/BackupRecoveryPhraseViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/backup/viewmodel/BackupSeedPhraseViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/restore/keystore/viewmodel/KeyStoreRestoreViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/restore/multirestore/viewmodel/MultiRestoreViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/wallet/confirm/presenter/WalletConfirmPresenter.kt
app/src/main/java/com/flowfoundation/wallet/utils/error/Error.kt
app/src/main/java/com/flowfoundation/wallet/utils/error/ErrorReporter.kt

feat: error code

---

app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/DeepLinkingActivity.kt
app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/PendingActionHelper.kt
app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/Utils.kt
app/src/main/java/com/flowfoundation/wallet/page/main/MainActivity.kt
app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/amount/SendAmountActivity.kt
app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/amount/SendAmountViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/amount/presenter/SendAmountPresenter.kt
app/src/main/java/com/flowfoundation/wallet/widgets/SwitchNetworkDialog.kt
app/src/main/res/values/strings.xml
gradle.properties

feat: use deeplink

---

app/src/main/java/com/flowfoundation/wallet/page/notification/model/WalletNotification.kt

fix: wallet notification null point time

---

app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/Utils.kt
app/src/main/java/com/flowfoundation/wallet/page/main/MainActivity.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values-en-rUS/strings.xml
app/src/main/res/values-es-rES/strings.xml
app/src/main/res/values-es-rUS/strings.xml
app/src/main/res/values-fr-rFR/strings.xml
app/src/main/res/values-hi-rIN/strings.xml
app/src/main/res/values-it-rIT/strings.xml
app/src/main/res/values-ja-rJP/strings.xml
app/src/main/res/values-ko-rKR/strings.xml
app/src/main/res/values-ru-rRU/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

fix: only navigate deeplink when user signed in

---

app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnectResponse.kt
app/src/main/java/com/flowfoundation/wallet/widgets/webview/fcl/Utils.kt

fix: restore the constructor of the account proof encode method

---

app/src/main/java/com/flowfoundation/wallet/manager/childaccount/ChildAccountList.kt
app/src/main/java/com/flowfoundation/wallet/page/nft/move/MoveNFTDialog.kt
app/src/main/java/com/flowfoundation/wallet/page/send/transaction/subpage/amount/presenter/SendAmountPresenter.kt
gradle.properties

Fix child account

---

app/src/main/java/com/flowfoundation/wallet/manager/childaccount/ChildAccountList.kt

fix: child account class cast exception

---

app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnect.kt
app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnectDelegate.kt
app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnectRequestDispatcher.kt
app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/DeepLinkingActivity.kt
app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/PendingActionHelper.kt
app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/Utils.kt
app/src/main/java/com/flowfoundation/wallet/widgets/webview/fcl/dialog/FclAuthnDialog.kt
app/src/main/res/values/strings.xml

- When WalletConnect connection request via deep link is missing redirect URL,handle the session connection and show a toast fallback indicating to return back to the browser
- Add a "Connecting..." toast which is shown from the beginning of the deep linking flow until the FCL Auth Dialog is fully rendered
-

Wallet Connect external browser redirect

---

app/src/main/java/com/flowfoundation/wallet/page/wallet/WalletFragmentViewModel.kt

fix: post staking info

---

app/src/main/java/com/flowfoundation/wallet/page/token/detail/presenter/TokenDetailPresenter.kt

Fix token security info

---

app/src/main/java/com/flowfoundation/wallet/page/nft/move/MoveNFTDialog.kt

feat: move nft evm address check

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/flowfoundation/wallet/page/browser/widgets/LilicoWebView.kt
app/src/main/java/com/flowfoundation/wallet/page/component/deeplinking/Utils.kt
app/src/main/java/com/flowfoundation/wallet/widgets/webview/JsInterface.kt
app/src/main/res/values/strings.xml

- https://github.com/onflow/FRW-Android/issues/1072
Support deep links with "tg" scheme.

Hot fix - telegram deep linking

---

app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/WalletConnect.kt
app/src/main/java/com/flowfoundation/wallet/page/profile/presenter/ProfileFragmentPresenter.kt

fix: walletconnect clean up session

---

app/src/main/java/com/flowfoundation/wallet/manager/walletconnect/Utils.kt

Fix walletconnect method error

---

app/src/main/java/com/flowfoundation/wallet/firebase/auth/FirebaseAuth.kt
gradle.properties

fix: login jwt force refresh

---

app/src/main/java/com/flowfoundation/wallet/manager/token/FungibleTokenListManager.kt
gradle.properties

fix: duplicate token list

---

app/src/main/java/com/flowfoundation/wallet/firebase/auth/FirebaseAuth.kt
app/src/main/java/com/flowfoundation/wallet/manager/token/FungibleTokenListManager.kt
gradle.properties

Merge r2.8.7 with code 299 from develop to master

---

app/src/main/java/com/flowfoundation/wallet/manager/config/NftCollectionConfig.kt
app/src/main/java/com/flowfoundation/wallet/network/model/NFTContractType.kt
app/src/main/java/com/flowfoundation/wallet/network/model/NFTListResponse.kt
app/src/main/java/com/flowfoundation/wallet/page/nft/nftdetail/presenter/NftDetailPresenter.kt
app/src/main/java/com/flowfoundation/wallet/page/nft/nftlist/presenter/NFTListItemPresenter.kt
app/src/main/java/com/flowfoundation/wallet/page/send/nft/confirm/NftSendConfirmViewModel.kt
app/src/main/java/com/flowfoundation/wallet/page/send/nft/confirm/presenter/NftSendConfirmPresenter.kt
app/src/main/res/drawable/ic_amount_minus.xml
app/src/main/res/drawable/ic_amount_plus.xml
app/src/main/res/layout/activity_nft_detail.xml
app/src/main/res/layout/dialog_send_confirm.xml
app/src/main/res/layout/item_nft_list.xml
app/src/main/res/values/strings.xml
gradle.properties

feat: add erc-1155 nft transfer amount
